databases:
  - name: coffee-proximity-db
    plan: free
    databaseName: coffee_proximity_finder_production
    user: coffee_proximity_finder

services:
  - type: web
    name: coffee-proximity-finder
    runtime: ruby
    plan: free
    buildCommand: "bundle install && bin/rails assets:precompile && bin/rails db:migrate && bin/rails runner 'CoffeeShops::Synchronizer.new.call'"
    startCommand: "bin/rails server -b 0.0.0.0 -p $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coffee-proximity-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: CSV_SOURCE_URL
        value: https://raw.githubusercontent.com/Agilefreaks/test_oop/master/coffee_shops.csv

